name: restaurant_app
description: Flutter Lokarasa Restaurant App

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  avatar_glow: ^3.0.1
  bloc: ^8.1.2
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.5
  dio: ^5.1.2
  either_dart: ^0.4.0
  equatable: ^2.0.5
  expandable_text: ^2.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_flavorizr: ^2.2.1
  flutter_hooks: ^0.20.5
  flutter_launcher_icons: "^0.13.1"
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.4
  gap: ^3.0.1
  get: ^4.6.6
  get_it: ^7.6.0
  go_router: ^13.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  injectable: ^2.1.1
  intl: ^0.18.1
  json_annotation: ^4.8.1
  logger: ^1.3.0
  lottie: ^3.0.0
  provider: ^6.1.1
  retrofit: ^4.0.1
  shared_preferences: ^2.1.1
  url_launcher: ^6.2.4

dev_dependencies:
  build_runner: ^2.4.4
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.5
  json_serializable: ^6.7.0
  retrofit_generator: ^7.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/font/
    - assets/svg/
    - assets/lottie/

  fonts:
    - family: PoppinsLight
      fonts:
        - asset: assets/font/Poppins-Light.ttf
    - family: PoppinsRegular
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
    - family: PoppinsMedium
      fonts:
        - asset: assets/font/Poppins-Medium.ttf
    - family: PoppinsBold
      fonts:
        - asset: assets/font/Poppins-Bold.ttf
    - family: PoppinsBlack
      fonts:
        - asset: assets/font/Poppins-Bold.ttf

# App Flavor Production and Staging
flavorizr:
  app:
    android:
      flavorDimensions: "api"
  flavors:
    production:
      app:
        name: "Lokarasa App"
      android:
        applicationId: "com.ristudev.lokarasa"
      ios:
        bundleId: "com.ristudev.lokarasa"
    development:
      app:
        name: "Lokarasa App"
      android:
        applicationId: "com.ristudev.lokarasa"
      ios:
        bundleId: "com.ristudev.lokarasa"
