name: restaurant_app
description: Flutter Restaurant App

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  bloc: ^8.1.2
  cupertino_icons: ^1.0.5
  dio: ^5.1.2
  either_dart: ^0.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  fluttertoast: ^8.2.4
  gap: ^3.0.1
  get: ^4.6.6
  get_it: ^7.6.0
  go_router: ^13.1.0
  injectable: ^2.1.1
  intl: ^0.18.1
  json_annotation: ^4.8.1
  logger: ^1.3.0
  lottie: ^3.0.0
  provider: ^6.1.1
  retrofit: ^4.0.1
  shared_preferences: ^2.1.1

dev_dependencies:
  build_runner: ^2.4.4
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.5
  json_serializable: ^6.7.0
  retrofit_generator: ^7.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/font/
    - assets/svg/
    - assets/lottie/

  fonts:
    - family: PoppinsLight
      fonts:
        - asset: assets/font/Poppins-Light.ttf
    - family: PoppinsRegular
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
    - family: PoppinsMedium
      fonts:
        - asset: assets/font/Poppins-Medium.ttf
    - family: PoppinsBold
      fonts:
        - asset: assets/font/Poppins-Bold.ttf
    - family: PoppinsBlack
      fonts:
        - asset: assets/font/Poppins-Bold.ttf
